### ISSUE TITLE
case insensitive..

### ISSUE THREAD

**Issue by ShoGinn** [AF-VCD/pdf-bullets#19]
This is probably related to #7 
But case shouldn't matter..

![Screen Shot 2020-02-05 at 3 30 05 PM](https://user-images.githubusercontent.com/2660603/73880808-25047a00-482d-11ea-974e-4f7655a6aba0.png)

**Comment by ckhordiasma** [comment]
For me it ended up being a non issue, because all words except proper nouns are required to be lower case unless they are an acronym. 

Except when the word is the first word of the bullet, but my leadership has a policy of not abbreviating the first word as well. 

Regardless, I am working on adding an option to enable case sensitive matching.

**Comment by ShoGinn** [comment]
Good Point, I guess my example was very generic. "Weapons Officers" is a better example which breaks that rule (not sure why I chose to use "Military Officer" maybe because it showed 2 abbreviations.. 
But your fix action should account for that.
